# Generated by Django 5.1.3 on 2024-12-03 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gas_type', models.CharField(choices=[('CO', 'Carbon Monoxide'), ('CO2', 'Carbon Dioxide'), ('CH4', 'Methane'), ('O2', 'Oxygen'), ('VOC', 'Volatile Organic Compounds')], default='CO', help_text='Type of gas being measured', max_length=10)),
                ('temperature', models.FloatField(help_text='Temperature in the environment')),
                ('unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', help_text='Unit of temperature', max_length=2)),
                ('gas_concentration', models.FloatField(help_text='Concentration of the gas')),
                ('concentration_unit', models.CharField(choices=[('ppm', 'Parts Per Million'), ('ppb', 'Parts Per Billion')], default='ppm', help_text='Unit of gas concentration', max_length=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the data was recorded')),
                ('home', models.ForeignKey(help_text="The home associated with this door's status", on_delete=django.db.models.deletion.CASCADE, related_name='gas', to='home.home')),
            ],
        ),
    ]
